# Generated by Django 6.0.3 on 2026-03-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("structure", models.JSONField(verbose_name="Структура данных")),
                ("data", models.JSONField(verbose_name="Данные")),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Путь к файлу"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, verbose_name="Код поля")),
                ("order", models.IntegerField(verbose_name="Порядковый номер")),
                ("name", models.CharField(max_length=100, verbose_name="Наименование")),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "Строка"),
                            ("date", "Дата"),
                            ("number", "Число"),
                        ],
                        max_length=10,
                        verbose_name="Тип данных",
                    ),
                ),
                (
                    "precision",
                    models.IntegerField(default=0, verbose_name="Точность (для чисел)"),
                ),
                (
                    "is_transferred",
                    models.BooleanField(default=True, verbose_name="Передавать"),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "exchange",
                    models.CharField(
                        choices=[
                            ("MOEX", "Московская биржа"),
                            ("SPB", "СПБ Биржа"),
                            ("FOREX", "Forex"),
                            ("CBR", "ЦБ РФ"),
                        ],
                        max_length=10,
                        verbose_name="Биржа",
                    ),
                ),
                ("rate", models.FloatField(verbose_name="Курс USD")),
                (
                    "source",
                    models.CharField(
                        max_length=100, verbose_name="Источник информации"
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "exchange"],
            },
        ),
    ]
